# Generated by Django 5.2.17 on 2026-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload your certificate PDF or image.', null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, default='Chennai', max_length=120),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='Chennai', max_length=120),
        ),
    ]
