# Generated by Django 5.2.17 on 2026-10-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certification_certificate_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('draft_type', models.CharField(help_text='e.g. Project, Experience, Achievement', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
