# Generated by Django 5.2.17 on 2026-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_draftitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftItem',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
