# Generated by Django 5.2.17 on 2026-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='List key project features (e.g. AI matching, Live chat).'),
        ),
    ]
